AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 'ami-0c55b159cbfafe1f0'  # Example AMI ID
      InstanceType: 't2.micro'
      KeyName: 'my-key-pair'
